language: generic
git:
  depth: 3
sudo: required
services:
  - docker

before_install:
  - docker build -t mosimane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mosimane/docker-react npm run test
  - git status

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
