language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mosimane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mosimane/docker-react npm run test
