version: '3'

services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/www/sites/docker-react/node_modules
      - .:/var/www/sites/docker-react
  tests:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /var/www/sites/docker-react/node_modules
      - .:/var/www/sites/docker-react
    command: ["npm", "run", "test"]

